<?php
use Doctrine\ORM\Mapping AS ORM;

/**
 * @ORM\Entity
 * @ORM\Table(
 *     name="country",
 *     indexes={
 *         @ORM\Index(name="FK_country_population_parameter", columns={"id_population_parameter"}),
 *         @ORM\Index(name="FK_country_currency", columns={"id_currency"})
 *     }
 * )
 */
class Country
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer", name="id_country", options={})
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idCountry;

    /**
     * @ORM\Column(type="string", length=50, nullable=false, name="country_name", options={"fixed":false})
     */
    private $countryName;

    /**
     * @ORM\ManyToOne(targetEntity="Currency", orphanRemoval=false)
     * @ORM\JoinColumn(name="id_currency", referencedColumnName="id_currency")
     */
    private $idCurrency;

    /**
     * @ORM\ManyToOne(targetEntity="PopulationParameter", orphanRemoval=false)
     * @ORM\JoinColumn(name="id_population_parameter", referencedColumnName="id_population_parameter")
     */
    private $idPopulationParameter;
}