BusinessField:
    type: entity
    table: business_field
    id:
        idBusinessField:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_business_field
            generator:
                strategy: IDENTITY
    fields:
        businessFieldName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: business_field_name
    lifecycleCallbacks: {  }
