ColectivityParameters:
    type: entity
    table: colectivity_parameters
    indexes:
        IDX_609F352EF864219C:
            columns:
                - id_collectivity
    uniqueConstraints:
        id_collectivity_date_of_information_type_collectivity:
            columns:
                - id_collectivity
                - date_of_information
                - type_collectivity
    id:
        idCollectiviteParams:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_collectivite_params
            generator:
                strategy: IDENTITY
    fields:
        dateOfInformation:
            type: date
            nullable: false
            column: date_of_information
        typeCollectivity:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                comment: 'pays, provinces, region'
            column: type_collectivity
        averageLocalDensity:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: average_local_density
        localSurface:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: local_surface
        averageLocalQualificationLev:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: average_local_qualification_lev
        averageLocalCostLabour:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: average_local_cost_labour
        localTemperature:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: local_temperature
        grossDomesticProduct:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: gross_domestic_product
    manyToOne:
        idCollectivity:
            targetEntity: Collectivity
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_collectivity:
                    referencedColumnName: id_collectivity
            orphanRemoval: false
    lifecycleCallbacks: {  }
