Collectivity:
    type: entity
    table: collectivity
    indexes:
        FK_collectivity_country:
            columns:
                - id_country
    id:
        idCollectivity:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_collectivity
            generator:
                strategy: IDENTITY
    fields:
        collectivityName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: collectivity_name
        typeCollectivity:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: type_collectivity
    manyToOne:
        idCountry:
            targetEntity: Country
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_country:
                    referencedColumnName: id_country
            orphanRemoval: false
    lifecycleCallbacks: {  }
