CompanyIndustry:
    type: entity
    table: company_industry
    id:
        idCompanyIndustry:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_company_industry
            generator:
                strategy: IDENTITY
    fields:
        industryName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: industry_name
    lifecycleCallbacks: {  }
