CompanySector:
    type: entity
    table: company_sector
    id:
        idCompanySector:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_company_sector
            generator:
                strategy: IDENTITY
    fields:
        sectorName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: sector_name
    lifecycleCallbacks: {  }
