Ressource:
    type: entity
    table: ressource
    indexes:
        FK_ressource_ressource_categorie:
            columns:
                - id_ressource_categorie
    id:
        idRessource:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_ressource
            generator:
                strategy: IDENTITY
    fields:
        ressourceName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: ressource_name
    manyToOne:
        idRessourceCategorie:
            targetEntity: RessourceCategorie
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_ressource_categorie:
                    referencedColumnName: id_ressource_categorie
            orphanRemoval: false
    lifecycleCallbacks: {  }
