RessourceCategorie:
    type: entity
    table: ressource_categorie
    id:
        idRessourceCategorie:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_ressource_categorie
            generator:
                strategy: IDENTITY
    fields:
        categoryRessource:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: category_ressource
    lifecycleCallbacks: {  }
