User:
    type: entity
    table: user
    id:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_user
            generator:
                strategy: IDENTITY
    fields:
        idCountry:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_country
        firstName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: last_name
        birthDate:
            type: date
            nullable: false
            column: birth_date
        emailAdress:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: email_adress
        profession:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 26
            options:
                fixed: false
    lifecycleCallbacks: {  }
