services:
    Heebari_data.user_registration:
        class: Heebari\dataBundle\EventListener\RegisterListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }

      