<?php
use Doctrine\ORM\Mapping AS ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="business_field")
 */
class BusinessField
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer", name="id_business_field", options={})
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idBusinessField;

    /**
     * @ORM\Column(type="string", length=50, nullable=false, name="business_field_name", options={"fixed":false})
     */
    private $businessFieldName;
}