<?php
use Doctrine\ORM\Mapping AS ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="company_sector")
 */
class CompanySector
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer", name="id_company_sector", options={})
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idCompanySector;

    /**
     * @ORM\Column(type="string", length=50, nullable=false, name="sector_name", options={"fixed":false})
     */
    private $sectorName;
}