<?php
use Doctrine\ORM\Mapping AS ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="ressource_categorie")
 */
class RessourceCategorie
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer", name="id_ressource_categorie", options={})
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idRessourceCategorie;

    /**
     * @ORM\Column(type="string", length=50, nullable=false, name="category_ressource", options={"fixed":false})
     */
    private $categoryRessource;
}