<?php

namespace Proxies\__CG__\Heebari\dataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CashFlowStatement extends \Heebari\dataBundle\Entity\CashFlowStatement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'idCashFlow', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'cashFlowDate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'cashFlowStatement', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'shortTermCashManagement', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'budget', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'idCompany'];
        }

        return ['__isInitialized__', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'idCashFlow', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'cashFlowDate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'cashFlowStatement', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'shortTermCashManagement', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'budget', '' . "\0" . 'Heebari\\dataBundle\\Entity\\CashFlowStatement' . "\0" . 'idCompany'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CashFlowStatement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCashFlow()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCashFlow();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCashFlow', []);

        return parent::getIdCashFlow();
    }

    /**
     * {@inheritDoc}
     */
    public function setCashFlowDate($cashFlowDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCashFlowDate', [$cashFlowDate]);

        return parent::setCashFlowDate($cashFlowDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCashFlowDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCashFlowDate', []);

        return parent::getCashFlowDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCashFlowStatement($cashFlowStatement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCashFlowStatement', [$cashFlowStatement]);

        return parent::setCashFlowStatement($cashFlowStatement);
    }

    /**
     * {@inheritDoc}
     */
    public function getCashFlowStatement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCashFlowStatement', []);

        return parent::getCashFlowStatement();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortTermCashManagement($shortTermCashManagement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortTermCashManagement', [$shortTermCashManagement]);

        return parent::setShortTermCashManagement($shortTermCashManagement);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortTermCashManagement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortTermCashManagement', []);

        return parent::getShortTermCashManagement();
    }

    /**
     * {@inheritDoc}
     */
    public function setBudget($budget)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBudget', [$budget]);

        return parent::setBudget($budget);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudget()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudget', []);

        return parent::getBudget();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCompany(\Heebari\dataBundle\Entity\Company $idCompany = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCompany', [$idCompany]);

        return parent::setIdCompany($idCompany);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCompany', []);

        return parent::getIdCompany();
    }

}
