<?php

namespace Proxies\__CG__\Heebari\dataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EconomicIndicator extends \Heebari\dataBundle\Entity\EconomicIndicator implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'idEconomicIndicator', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'dateOfInformation', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'gdpGrowth', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'priceIndexRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'investmentRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'nationalConsumptionRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'exportRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'importRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'incomeLevelRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'debtLevelRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'idEconomicData'];
        }

        return ['__isInitialized__', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'idEconomicIndicator', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'dateOfInformation', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'gdpGrowth', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'priceIndexRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'investmentRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'nationalConsumptionRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'exportRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'importRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'incomeLevelRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'debtLevelRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\EconomicIndicator' . "\0" . 'idEconomicData'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EconomicIndicator $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdEconomicIndicator()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdEconomicIndicator();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEconomicIndicator', []);

        return parent::getIdEconomicIndicator();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfInformation($dateOfInformation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfInformation', [$dateOfInformation]);

        return parent::setDateOfInformation($dateOfInformation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfInformation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfInformation', []);

        return parent::getDateOfInformation();
    }

    /**
     * {@inheritDoc}
     */
    public function setGdpGrowth($gdpGrowth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGdpGrowth', [$gdpGrowth]);

        return parent::setGdpGrowth($gdpGrowth);
    }

    /**
     * {@inheritDoc}
     */
    public function getGdpGrowth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGdpGrowth', []);

        return parent::getGdpGrowth();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceIndexRate($priceIndexRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceIndexRate', [$priceIndexRate]);

        return parent::setPriceIndexRate($priceIndexRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceIndexRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceIndexRate', []);

        return parent::getPriceIndexRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvestmentRate($investmentRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvestmentRate', [$investmentRate]);

        return parent::setInvestmentRate($investmentRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvestmentRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvestmentRate', []);

        return parent::getInvestmentRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationalConsumptionRate($nationalConsumptionRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationalConsumptionRate', [$nationalConsumptionRate]);

        return parent::setNationalConsumptionRate($nationalConsumptionRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationalConsumptionRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationalConsumptionRate', []);

        return parent::getNationalConsumptionRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setExportRate($exportRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExportRate', [$exportRate]);

        return parent::setExportRate($exportRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExportRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExportRate', []);

        return parent::getExportRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setImportRate($importRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImportRate', [$importRate]);

        return parent::setImportRate($importRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getImportRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImportRate', []);

        return parent::getImportRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncomeLevelRate($incomeLevelRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncomeLevelRate', [$incomeLevelRate]);

        return parent::setIncomeLevelRate($incomeLevelRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncomeLevelRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncomeLevelRate', []);

        return parent::getIncomeLevelRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDebtLevelRate($debtLevelRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebtLevelRate', [$debtLevelRate]);

        return parent::setDebtLevelRate($debtLevelRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebtLevelRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebtLevelRate', []);

        return parent::getDebtLevelRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEconomicData(\Heebari\dataBundle\Entity\EconomicData $idEconomicData = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEconomicData', [$idEconomicData]);

        return parent::setIdEconomicData($idEconomicData);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEconomicData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEconomicData', []);

        return parent::getIdEconomicData();
    }

}
