<?php

namespace Proxies\__CG__\Heebari\dataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PopulationDistribution extends \Heebari\dataBundle\Entity\PopulationDistribution implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'idPopulationDistribution', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'gender', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'dateOfInformation', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'urbanisationRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'activityRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'unemploymentRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'qualificationLevel', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'bankingPenetrationRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'lifeExpectancy', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'mortalityRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'birthRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'idAgeRange'];
        }

        return ['__isInitialized__', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'idPopulationDistribution', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'gender', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'dateOfInformation', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'urbanisationRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'activityRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'unemploymentRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'qualificationLevel', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'bankingPenetrationRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'lifeExpectancy', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'mortalityRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'birthRate', '' . "\0" . 'Heebari\\dataBundle\\Entity\\PopulationDistribution' . "\0" . 'idAgeRange'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PopulationDistribution $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPopulationDistribution()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPopulationDistribution();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPopulationDistribution', []);

        return parent::getIdPopulationDistribution();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfInformation($dateOfInformation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfInformation', [$dateOfInformation]);

        return parent::setDateOfInformation($dateOfInformation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfInformation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfInformation', []);

        return parent::getDateOfInformation();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrbanisationRate($urbanisationRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrbanisationRate', [$urbanisationRate]);

        return parent::setUrbanisationRate($urbanisationRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrbanisationRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrbanisationRate', []);

        return parent::getUrbanisationRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivityRate($activityRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivityRate', [$activityRate]);

        return parent::setActivityRate($activityRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivityRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivityRate', []);

        return parent::getActivityRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnemploymentRate($unemploymentRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnemploymentRate', [$unemploymentRate]);

        return parent::setUnemploymentRate($unemploymentRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnemploymentRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnemploymentRate', []);

        return parent::getUnemploymentRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualificationLevel($qualificationLevel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualificationLevel', [$qualificationLevel]);

        return parent::setQualificationLevel($qualificationLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualificationLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualificationLevel', []);

        return parent::getQualificationLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLifeExpectancy($lifeExpectancy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLifeExpectancy', [$lifeExpectancy]);

        return parent::setLifeExpectancy($lifeExpectancy);
    }

    /**
     * {@inheritDoc}
     */
    public function getLifeExpectancy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLifeExpectancy', []);

        return parent::getLifeExpectancy();
    }

    /**
     * {@inheritDoc}
     */
    public function setMortalityRate($mortalityRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMortalityRate', [$mortalityRate]);

        return parent::setMortalityRate($mortalityRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getMortalityRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMortalityRate', []);

        return parent::getMortalityRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthRate($birthRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthRate', [$birthRate]);

        return parent::setBirthRate($birthRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthRate', []);

        return parent::getBirthRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAgeRange(\Heebari\dataBundle\Entity\AgeRange $idAgeRange = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAgeRange', [$idAgeRange]);

        return parent::setIdAgeRange($idAgeRange);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAgeRange()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAgeRange', []);

        return parent::getIdAgeRange();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankingPenetrationRate($bankingPenetrationRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankingPenetrationRate', [$bankingPenetrationRate]);

        return parent::setBankingPenetrationRate($bankingPenetrationRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankingPenetrationRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankingPenetrationRate', []);

        return parent::getBankingPenetrationRate();
    }

}
