<?php

namespace Proxies\__CG__\Heebari\dataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class IncomeStatement extends \Heebari\dataBundle\Entity\IncomeStatement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'idIncomeStatement', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'dateOfInformation', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'incomeStatement', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'sales', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'costOfGoodSold', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'grossProfit', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'sellingAdministrative', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'depreciationAndAmortization', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'ebit', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'interestAndFinancialCharges', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'idCompany'];
        }

        return ['__isInitialized__', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'idIncomeStatement', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'dateOfInformation', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'incomeStatement', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'sales', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'costOfGoodSold', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'grossProfit', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'sellingAdministrative', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'depreciationAndAmortization', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'ebit', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'interestAndFinancialCharges', '' . "\0" . 'Heebari\\dataBundle\\Entity\\IncomeStatement' . "\0" . 'idCompany'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (IncomeStatement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdIncomeStatement()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdIncomeStatement();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdIncomeStatement', []);

        return parent::getIdIncomeStatement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfInformation($dateOfInformation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfInformation', [$dateOfInformation]);

        return parent::setDateOfInformation($dateOfInformation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfInformation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfInformation', []);

        return parent::getDateOfInformation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncomeStatement($incomeStatement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncomeStatement', [$incomeStatement]);

        return parent::setIncomeStatement($incomeStatement);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncomeStatement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncomeStatement', []);

        return parent::getIncomeStatement();
    }

    /**
     * {@inheritDoc}
     */
    public function setSales($sales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSales', [$sales]);

        return parent::setSales($sales);
    }

    /**
     * {@inheritDoc}
     */
    public function getSales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSales', []);

        return parent::getSales();
    }

    /**
     * {@inheritDoc}
     */
    public function setCostOfGoodSold($costOfGoodSold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostOfGoodSold', [$costOfGoodSold]);

        return parent::setCostOfGoodSold($costOfGoodSold);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostOfGoodSold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostOfGoodSold', []);

        return parent::getCostOfGoodSold();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrossProfit($grossProfit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrossProfit', [$grossProfit]);

        return parent::setGrossProfit($grossProfit);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrossProfit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrossProfit', []);

        return parent::getGrossProfit();
    }

    /**
     * {@inheritDoc}
     */
    public function setSellingAdministrative($sellingAdministrative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSellingAdministrative', [$sellingAdministrative]);

        return parent::setSellingAdministrative($sellingAdministrative);
    }

    /**
     * {@inheritDoc}
     */
    public function getSellingAdministrative()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSellingAdministrative', []);

        return parent::getSellingAdministrative();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepreciationAndAmortization($depreciationAndAmortization)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepreciationAndAmortization', [$depreciationAndAmortization]);

        return parent::setDepreciationAndAmortization($depreciationAndAmortization);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepreciationAndAmortization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepreciationAndAmortization', []);

        return parent::getDepreciationAndAmortization();
    }

    /**
     * {@inheritDoc}
     */
    public function setEbit($ebit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEbit', [$ebit]);

        return parent::setEbit($ebit);
    }

    /**
     * {@inheritDoc}
     */
    public function getEbit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEbit', []);

        return parent::getEbit();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterestAndFinancialCharges($interestAndFinancialCharges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterestAndFinancialCharges', [$interestAndFinancialCharges]);

        return parent::setInterestAndFinancialCharges($interestAndFinancialCharges);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterestAndFinancialCharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterestAndFinancialCharges', []);

        return parent::getInterestAndFinancialCharges();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCompany(\Heebari\dataBundle\Entity\Company $idCompany = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCompany', [$idCompany]);

        return parent::setIdCompany($idCompany);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCompany', []);

        return parent::getIdCompany();
    }

}
